# 京东云亚瑟
name: JDCloud RE-SS-01

on:
  # 手动编译
  workflow_dispatch:
    inputs:
      PACKAGE:
        description: '手动调整插件包，多个请用\n符号隔开。'
        required: false
        type: string
      TEST:
        description: '仅输出配置文件，不编译固件。'
        default: 'false'
        required: false
        type: boolean

jobs:
  config:
    name: Build
    uses: ./.github/workflows/wrt-core.yml
    with:
      # 编译配置
      WRT_CONFIG: jdcloud-re-ss-01
      # 默认主机名
      WRT_NAME: RE-SS-01
      # 默认WIFI名称
      WRT_SSID: JDCloud-RE-SS-01
      # 默认WIFI密码
      WRT_WORD: 12345678
      # 默认登录IPd地
      WRT_IP: 192.168.1.1
      # 默认登录密码，仅作提示，修改无用
      WRT_PW: 无
      # 源码链接
      WRT_REPO: https://github.com/LiBwrt/openwrt-6.x.git
      # 源码分支
      WRT_BRANCH: k6.12-nss
      # 源码名称
      WRT_SOURCE: LiBwrt/openwrt-6.x
      # 插件调整
      WRT_PACKAGE: ${{inputs.PACKAGE}}
      # 仅输出配置文件
      WRT_TEST: ${{inputs.TEST}}
